type Room {
  name: String!
  timeLimit: String!
}
type Query {
  allRooms: [Room!]
  getRoomByName(name: String!): [Room]
}
type Mutation {
  addRoom(name: String!, timeLimit: String!): Room! @resolver
}
